3. Fin^ the shape, size an^ ^imension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [2]:
import numpy as np

In [17]:
a=[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]
array=np.array(a)

In [10]:
array.shape,array.size

((3, 4), 12)

In [ ]:
4. Write python co^e to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [21]:
array[0]

array([1, 2, 3, 4])

In [ ]:
5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [34]:
array[2,3]

12

In [ ]:
6. Write co^e to extract all o^^-in^exe^ elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [43]:
array[array%2!=0]

array([ 1,  3,  5,  7,  9, 11])

7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?

In [58]:
a4=np.eye(3,3)

In [ ]:
9. Write co^e to increase the ^imension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [62]:
a5=np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

In [76]:
np.expand_dims(a5,axis=1)

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [ ]:
10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [78]:
a5.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

11. Consi^er the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python1
,+ I(dex wiLe multiplicatio'
]+ Matix multiplicatio'
+ Add both the maticK
-+ Subtact matix B om 
+ Diide Matix B by A

In [87]:
Matrix1 = [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix2 =[[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]

In [88]:
Matrix1 =np.array(Matrix1)
Matrix2 =np.array(Matrix2)

In [90]:
Matrix1*Matrix2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [95]:
sum(Matrix1,Matrix2)

array([[16, 20, 24, 28],
       [20, 24, 28, 32],
       [24, 28, 32, 36]])

In [96]:
Matrix2-Matrix1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [97]:
Matrix1/Matrix2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [102]:
2*Matrix1[0:3]

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [104]:
3*Matrix2[0:3]

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

1. What is a Python library? Why ^o we use Python libraries?
2. What is the difference between Numpy array and List?

1 Python libraries are collections of pre-written code and functions that extend the capabilities of the Python programming language. They provide a wide range of tools and modules for various tasks, making it easier for developers to work on specific tasks without reinventing the wheel

2 The main difference is that NumPy arrays are much faster and have strict requirements on the homogeneity of the objects. For example, a NumPy array of strings can only contain strings and no other data types, but a Python list can contain a mixture of strings, numbers, booleans and other objects.

12. Which function in Numpy can be used to swap the byte order of an array?
13. What is the significance of the np.linalg.inv function?
14. What does the np.reshape function do, and how is it used?
15. What is broadcasting in Numpy?

12 byteswap() method swaps the bytes of the array elements. It toggles between low-endian and big-endian data representation by returning a byteswapped array, optionally swapped in-place

13 The np. linalg. inv() function in numpy provides a convenient and efficient way to calculate the inverse of a matrix in Python. It handles various edge cases and is widely used in scientific and engineering applications.

14 Change an Array's Shape Using NumPy reshape() NumPy's reshape() enables you to change the shape of an array into another compatible shape. Not all shapes are compatible since all the elements from the original array needs to fit into the new array. You can use reshape() as either a function or a method.

15 numpy.broadcast. The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.